on: [watch]

name: Packet Project Sample

jobs:
  deploy-new-project-and-device-batch:
    runs-on: ubuntu-latest
    name: Provisioning infrastructure
    steps:
      - name: Transfer SSH keys
        uses: mattdavis0351/packet-create-user-ssh-key@v1
        id: key
        with:
          API_key: ${{ secrets.PACKET_API_KEY }}
          #################################################
          key_label: charlie-actions # rename this for yourself
          #################################################
          public_key: ${{ secrets.PACKET_PUBLIC_KEY }}
      - name: Create new project
        uses: mattdavis0351/packet-create-project@v1
        if: success()
        id: project
        with:
          API_key: ${{ secrets.PACKET_API_KEY }}
          project_name: My-action-batch
      - name: Create new device batch
        uses: mattdavis0351/packet-create-device-batch@master
        if: success()
        with:
          API_key: ${{ secrets.PACKET_API_KEY }}
          project_name: ${{steps.project.outputs.project_name}}
          host_names: "K8s-Master, K8s-minion-1, K8s-minion-2 "
          plan: "t3.small.x86"
          facility: "sjc1"
          operating_system: "ubuntu_19_04"
          quantity: 3
          spot_instance: true
          spot_price_max: .50
          user_ssh_keys: ${{ secrets.PACKET_PUBLIC_KEY }}
